-- ============================================================
-- Media Source Columns Migration
-- Purpose: Track source type and URL for media-backed tabs
--          (audio, video, PDF, or plain text)
-- Date: March 2026
-- ============================================================

-- source_type: what kind of source content this tab was built from
ALTER TABLE public.tabs
  ADD COLUMN IF NOT EXISTS source_type TEXT DEFAULT 'text'
    CHECK (source_type IN ('text', 'pdf', 'audio', 'video'));

-- source_url: the original media URL (YouTube link, podcast MP3, PDF URL, etc.)
-- Distinct from file_url which is for downloadable files in Supabase storage.
-- source_url points to the *input* used to generate tabs.content via processing.
ALTER TABLE public.tabs
  ADD COLUMN IF NOT EXISTS source_url TEXT;

-- media_metadata: processing details (duration, speaker count, language, etc.)
ALTER TABLE public.tabs
  ADD COLUMN IF NOT EXISTS media_metadata JSONB DEFAULT '{}'::jsonb;

-- Index for filtering by source type
CREATE INDEX IF NOT EXISTS idx_tabs_source_type
  ON public.tabs (source_type);

-- ============================================================
-- Usage:
--   source_type = 'text'  → content was written/pasted directly
--   source_type = 'pdf'   → content generated by process-pdf
--   source_type = 'audio' → content generated by process-media (MP3, podcast)
--   source_type = 'video' → content generated by process-media (MP4, YouTube)
--
-- source_url examples:
--   'https://www.youtube.com/watch?v=abc123'
--   'https://drive.google.com/file/d/xxx/view?usp=sharing'
--   'https://podcast-host.com/episodes/ep42.mp3'
--   'https://xyzproject.supabase.co/storage/v1/object/public/docs/report.pdf'
-- ============================================================
